[theme]
primaryColor="#ad310bff"
backgroundColor="#0e1117"
secondaryBackgroundColor="#6aa8b3ff"
textColor="#f8f5f5ff"
font = "Raleway, sans-serif"
headingFont = "Playfair Display, serif"
codeFont = "Fira Code, monospace"



              